### PR TITLE
Enable the library extension to be used as a standalone plugin, and update for 2018.3

### PR DESCRIPTION
**Pull request by gehnaphore**

### CODE REVIEW

**Comment by shadaj** [comment]
Do you know if this would still work with 2018.2? Otherwise the version boundaries should probably be changed. Otherwise looks good!

**Comment by baank** [comment]
I have a Button defined as such:

`@react class Button extends StatelessComponent {

	case class Props(title: String,
                                      size: Size = Size.Default,
				      style: ButtonStyle = ButtonStyle.Default,
				      icon: Option[String] = None)
`

Works: `Button(title = "MyTitle")`
Doesn't work: `Button(title = "MyTitle", icon=Some("MyIcon")`

Error: Too many arguments for method apply()(Unit =:= BaseComponentWrapper.this.Props, ConstructorTag.

Looks to be related to this plugin (I am using this fork). I am looking into this.
